# Generated by Django 4.0.1 on 2022-01-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0011_alter_userextradata_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextradata',
            name='avatar',
        ),
    ]
