# Generated by Django 4.0.1 on 2022-01-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0013_alter_userextradata_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='site_app.UserImages'),
        ),
    ]
