# Generated by Django 4.0.1 on 2022-01-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0017_remove_votes_contest_votes_contest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimages',
            old_name='date_time_uploaded',
            new_name='date_uploaded',
        ),
    ]
