# Generated by Django 3.2.7 on 2021-09-20 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=13)),
                ('date_birth', models.DateField(null=True)),
                ('datetime_registered', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дельтовец',
                'verbose_name_plural': 'Дельтовцы',
            },
        ),
    ]
