# Generated by Django 3.2.7 on 2021-10-08 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextradata',
            name='datetime_registered',
        ),
    ]
