# Generated by Django 4.0.1 on 2022-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_alter_userextradata_date_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='date_time_uploaded',
            field=models.DateField(auto_now=True),
        ),
    ]
