# Generated by Django 4.0.1 on 2022-01-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_contest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='date_finished',
            field=models.DateField(default='2010-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='date_started',
            field=models.DateField(auto_now=True),
        ),
    ]
