# Generated by Django 4.0.1 on 2022-01-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_contest_date_finished_contest_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextradata',
            name='avatar',
            field=models.ImageField(upload_to='pictures/avatars'),
        ),
    ]
