# Generated by Django 4.0.1 on 2022-01-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0016_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='Contest',
        ),
        migrations.AddField(
            model_name='votes',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='site_app.contest'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PictureContestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.contest')),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='site_app.userimages')),
            ],
        ),
    ]
