# Generated by Django 4.0.1 on 2022-02-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0022_alter_votes_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecontestrating',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.userimages'),
        ),
    ]
