# Generated by Django 4.0.3 on 2022-03-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0025_quizstatement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizstatement',
            options={'verbose_name': 'Викторина', 'verbose_name_plural': 'Викторины'},
        ),
    ]
