# Generated by Django 4.0.3 on 2022-04-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0026_alter_quizstatement_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizStatement',
        ),
    ]
